version: '3'
services:
  srvapp:
    image: freeshareback
    volumes:
    - download:/home/node/app/download
    - vignette:/home/node/app/vignette


    ports:
    - "4100:3000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "41017:27017"
    volumes:
    - db:/data/db

volumes:
  download:
  vignette:
  db:
